### PR TITLE
ENHANCEMENT ElementJobListings

### LINKED ISSUE #21: ENHANCEMENT element to display job postings
**Features**
- [ ] Display N number of job postings based on optional criteria
    - [ ] Parent Job Collection page
    - [ ] Job Category
    - [ ] Limit number of jobs to display
- [ ] Select specific job(s) to be displayed

### PR DESCRIPTION
**Pull request by muskie9**
resolves #21

### CODE REVIEW

**Comment by jsirish** [comment]
@muskie9 want me to wrap this one up?

**Comment by muskie9** [comment]
Ya, I think this will be useful in the near future.

**Comment by jsirish** [comment]
@muskie9 should be in good shape, may solve some issues for me on our site

**Comment by muskie9** [comment]
Looks good. Might have some adjustments down the road, but it seems to work great!

**Pull request merged**
